# Generated by Django 2.2.5 on 2021-01-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
